REM   Script: Assignment 3
REM   Assignment 3

SELECT e.EMPNO AS "Employee Number",  
       e.ENAME AS "Employee Name",  
       e.HIREDATE AS "Hiredate",  
       m.ENAME AS "Mgr Name" 
FROM EMP e 
JOIN EMP m ON e.MGR = m.EMPNO 
WHERE m.ENAME LIKE 'K%'  
   OR m.ENAME LIKE 'M%'  
   OR m.ENAME LIKE 'S%';

DROP TABLE EMP CASCADE CONSTRAINTS;

DROP TABLE DEPT;

DROP TABLE EMP CASCADE CONSTRAINTS;

DROP TABLE DEPT;

DROP TABLE SALGRADE;

DROP TABLE Prod CASCADE CONSTRAINTS;

DROP TABLE Vend;

CREATE TABLE DEPT ( 
DEPTNO NUMBER(2) NOT NULL, 
DNAME CHAR(14), 
LOC CHAR(13), 
CONSTRAINT DEPT_PRIMARY_KEY PRIMARY KEY (DEPTNO));

INSERT INTO DEPT VALUES (10,'ACCOUNTING','NEW YORK');

INSERT INTO DEPT VALUES (20,'RESEARCH','DALLAS');

INSERT INTO DEPT VALUES (30,'SALES','CHICAGO');

INSERT INTO DEPT VALUES (40,'OPERATIONS','BOSTON');

CREATE TABLE EMP ( 
EMPNO NUMBER(4) NOT NULL, 
ENAME CHAR(10), 
JOB CHAR(9), 
MGR NUMBER(4) CONSTRAINT EMP_SELF_KEY 
REFERENCES EMP (EMPNO), 
HIREDATE DATE, 
SAL NUMBER(7,2), 
COMM NUMBER(7,2), 
DEPTNO NUMBER(2) NOT NULL, 
CONSTRAINT EMP_FOREIGN_KEY FOREIGN KEY (DEPTNO) REFERENCES DEPT (DEPTNO), 
CONSTRAINT EMP_PRIM_KEY PRIMARY KEY (EMPNO));

INSERT INTO EMP VALUES (7839,'KING','PRESIDENT',NULL,'17-NOV-1981',5000,NULL,10);

INSERT INTO EMP VALUES (7698,'BLAKE','MANAGER',7839,'1-MAY-1981',2850,NULL,30);

INSERT INTO EMP VALUES (7782,'CLARK','MANAGER',7839,'9-JUN-1981',2450,NULL,10);

INSERT INTO EMP VALUES (7566,'JONES','MANAGER',7839,'2-APR-1981',2975,NULL,20);

INSERT INTO EMP VALUES (7654,'MARTIN','SALESMAN',7698,'28-SEP-1981',1250,1400,30);

INSERT INTO EMP VALUES (7499,'ALLEN','SALESMAN',7698,'20-FEB-1981',1600,300,30);

INSERT INTO EMP VALUES (7844,'TURNER','SALESMAN',7698,'8-SEP-1981',1500,0,30);

INSERT INTO EMP VALUES (7900,'JAMES','CLERK',7698,'3-DEC-1981',950,NULL,30);

INSERT INTO EMP VALUES (7521,'WARD','SALESMAN',7698,'22-FEB-1981',1250,500,30);

INSERT INTO EMP VALUES (7902,'FORD','ANALYST',7566,'3-DEC-1981',3000,NULL,20);

INSERT INTO EMP VALUES (7369,'SMITH','CLERK',7902,'17-DEC-1980',800,NULL,20);

INSERT INTO EMP VALUES (7788,'SCOTT','ANALYST',7566,'09-DEC-1982',3000,NULL,20);

INSERT INTO EMP VALUES (7876,'ADAMS','CLERK',7788,'12-JAN-1983',1100,NULL,20);

INSERT INTO EMP VALUES (7934,'MILLER','CLERK',7782,'23-JAN-1982',1300,NULL,10);

CREATE TABLE SALGRADE ( 
GRADE NUMBER, 
LOSAL NUMBER, 
HISAL NUMBER);

INSERT INTO SALGRADE VALUES (1,700,1200);

INSERT INTO SALGRADE VALUES (2,1201,1400);

INSERT INTO SALGRADE VALUES (3,1401,2000);

INSERT INTO SALGRADE VALUES (4,2001,3000);

INSERT INTO SALGRADE VALUES (5,3001,9999);

CREATE TABLE Prod 
( ProdNo NUMBER(4) NOT NULL, 
PName CHAR(10), 
Type CHAR(4), 
Family NUMBER(4), 
Price NUMBER(7,2), 
Disc NUMBER(3,1), 
IntroDate DATE, 
VendNo NUMBER(4), 
Inv NUMBER(3), 
PRIMARY KEY (ProdNo));

INSERT INTO Prod VALUES ( 
4186, 'Lotus 123', 'SPSH', 2215, 399.95, 25, '08-MAY-1990' ,26, 35);

INSERT INTO Prod VALUES ( 
2215, 'Windows', 'OS', 7224, 129, 40, '15-JUN-1990' ,12, 123);

INSERT INTO Prod VALUES ( 
6240, 'AmiPro', 'WP', 2215, 295.5, 33.3, '01-JUN-1990' ,26, 17);

INSERT INTO Prod VALUES ( 
7224, 'MS-DOS', 'OS', NULL, 99.95, 30, '03-MAR-1991' ,12, 88);

INSERT INTO Prod VALUES ( 
3055, 'Lotus 123', 'SPSH', 3088, 399.95, 0, '18-OCT-1990' ,26, 12);

INSERT INTO Prod VALUES ( 
3088, 'Macintosh', 'OS', NULL, 149.95, NULL, '12-DEC-1989' ,41, 142);

INSERT INTO Prod VALUES ( 
1108, 'Finance', 'BUS', 4186, 99.95, NULL, '22-APR-1991' ,82, 16);

INSERT INTO Prod VALUES ( 
9167, 'Lotus 123', 'SPSH', 7224, 399.95, 35, '26-FEB-1989' ,26, 71);

INSERT INTO Prod VALUES ( 
4925, 'Paradox', 'DBMS', 7224, 345, 25, '21-SEP-1989' ,55, 64);

INSERT INTO Prod VALUES ( 
1067, 'Finance', 'BUS', 9167, 99.95, NULL, '07-MAR-1989' ,82, 0);

INSERT INTO Prod VALUES ( 
6482, 'BusPlan', 'BUS', 4186, 54.5, 10, '05-JAN-1991' ,82, 41);

INSERT INTO Prod VALUES ( 
7190, 'BusPlan', 'BUS', 9167, 54.5, 10, '14-FEB-1989' ,82, NULL);

INSERT INTO Prod VALUES ( 
6888, 'BusPlan', 'BUS', 3055, 54.5, 0, '14-FEB-1989' ,82, 26);

INSERT INTO Prod VALUES ( 
3981, 'SQL*Report', 'DBMS', 5476, 149.5, 0, '22-SEP-1990' ,58, 12);

INSERT INTO Prod VALUES ( 
9482, 'Quattro', 'SPSH', 7224, 199.95, 30, '24-AUG-1990' ,55, 53);

INSERT INTO Prod VALUES ( 
5476, 'Oracle', 'DBMS', 7224, 895, 5, '12-SEP-1990' ,58, 38);

INSERT INTO Prod VALUES ( 
3007, 'Finance', 'BUS', 9482, 99.95, NULL, '06-NOV-1990' ,82, 17);

INSERT INTO Prod VALUES ( 
8120, 'Inventory', 'BUS', 9482, 199.5, 10, '06-NOV-1990' ,82, 0);

INSERT INTO Prod VALUES ( 
1830, 'SQL*Plus', 'DBMS', 5476, 199.5, 5, '06-OCT-1990' ,58, 19);

CREATE TABLE Vend 
( VName CHAR(10), 
VState CHAR(2), 
VendNo NUMBER(2) NOT NULL, 
Acct CHAR(5), 
PRIMARY KEY (VendNo));

INSERT INTO Vend VALUES ( 
'Apple', 'CA', 41, 'COD');

INSERT INTO Vend VALUES ( 
'Oracle', 'CA', 58, '30');

INSERT INTO Vend VALUES ( 
'Lotus', 'UT', 26, '30');

INSERT INTO Vend VALUES ( 
'Microsoft', 'WA', 12, '10');

INSERT INTO Vend VALUES ( 
'Acme', 'UT', 82, 'COD');

INSERT INTO Vend VALUES ( 
'Borland', 'CA', 55, '30');

INSERT INTO Vend VALUES ( 
'Ace', 'OR', 67, '30');

COMMIT;

DROP TABLE SALGRADE;

DROP TABLE Prod CASCADE CONSTRAINTS;

DROP TABLE Vend;

CREATE TABLE DEPT ( 
DEPTNO NUMBER(2) NOT NULL, 
DNAME CHAR(14), 
LOC CHAR(13), 
CONSTRAINT DEPT_PRIMARY_KEY PRIMARY KEY (DEPTNO));

INSERT INTO DEPT VALUES (10,'ACCOUNTING','NEW YORK');

INSERT INTO DEPT VALUES (20,'RESEARCH','DALLAS');

INSERT INTO DEPT VALUES (30,'SALES','CHICAGO');

INSERT INTO DEPT VALUES (40,'OPERATIONS','BOSTON');

CREATE TABLE EMP ( 
EMPNO NUMBER(4) NOT NULL, 
ENAME CHAR(10), 
JOB CHAR(9), 
MGR NUMBER(4) CONSTRAINT EMP_SELF_KEY 
REFERENCES EMP (EMPNO), 
HIREDATE DATE, 
SAL NUMBER(7,2), 
COMM NUMBER(7,2), 
DEPTNO NUMBER(2) NOT NULL, 
CONSTRAINT EMP_FOREIGN_KEY FOREIGN KEY (DEPTNO) REFERENCES DEPT (DEPTNO), 
CONSTRAINT EMP_PRIM_KEY PRIMARY KEY (EMPNO));

INSERT INTO EMP VALUES (7839,'KING','PRESIDENT',NULL,'17-NOV-1981',5000,NULL,10);

INSERT INTO EMP VALUES (7698,'BLAKE','MANAGER',7839,'1-MAY-1981',2850,NULL,30);

INSERT INTO EMP VALUES (7782,'CLARK','MANAGER',7839,'9-JUN-1981',2450,NULL,10);

INSERT INTO EMP VALUES (7566,'JONES','MANAGER',7839,'2-APR-1981',2975,NULL,20);

INSERT INTO EMP VALUES (7654,'MARTIN','SALESMAN',7698,'28-SEP-1981',1250,1400,30);

INSERT INTO EMP VALUES (7499,'ALLEN','SALESMAN',7698,'20-FEB-1981',1600,300,30);

INSERT INTO EMP VALUES (7844,'TURNER','SALESMAN',7698,'8-SEP-1981',1500,0,30);

INSERT INTO EMP VALUES (7900,'JAMES','CLERK',7698,'3-DEC-1981',950,NULL,30);

INSERT INTO EMP VALUES (7521,'WARD','SALESMAN',7698,'22-FEB-1981',1250,500,30);

INSERT INTO EMP VALUES (7902,'FORD','ANALYST',7566,'3-DEC-1981',3000,NULL,20);

INSERT INTO EMP VALUES (7369,'SMITH','CLERK',7902,'17-DEC-1980',800,NULL,20);

INSERT INTO EMP VALUES (7788,'SCOTT','ANALYST',7566,'09-DEC-1982',3000,NULL,20);

INSERT INTO EMP VALUES (7876,'ADAMS','CLERK',7788,'12-JAN-1983',1100,NULL,20);

INSERT INTO EMP VALUES (7934,'MILLER','CLERK',7782,'23-JAN-1982',1300,NULL,10);

CREATE TABLE SALGRADE ( 
GRADE NUMBER, 
LOSAL NUMBER, 
HISAL NUMBER);

INSERT INTO SALGRADE VALUES (1,700,1200);

INSERT INTO SALGRADE VALUES (2,1201,1400);

INSERT INTO SALGRADE VALUES (3,1401,2000);

INSERT INTO SALGRADE VALUES (4,2001,3000);

INSERT INTO SALGRADE VALUES (5,3001,9999);

CREATE TABLE Prod 
( ProdNo NUMBER(4) NOT NULL, 
PName CHAR(10), 
Type CHAR(4), 
Family NUMBER(4), 
Price NUMBER(7,2), 
Disc NUMBER(3,1), 
IntroDate DATE, 
VendNo NUMBER(4), 
Inv NUMBER(3), 
PRIMARY KEY (ProdNo));

INSERT INTO Prod VALUES ( 
4186, 'Lotus 123', 'SPSH', 2215, 399.95, 25, '08-MAY-1990' ,26, 35);

INSERT INTO Prod VALUES ( 
2215, 'Windows', 'OS', 7224, 129, 40, '15-JUN-1990' ,12, 123);

INSERT INTO Prod VALUES ( 
6240, 'AmiPro', 'WP', 2215, 295.5, 33.3, '01-JUN-1990' ,26, 17);

INSERT INTO Prod VALUES ( 
7224, 'MS-DOS', 'OS', NULL, 99.95, 30, '03-MAR-1991' ,12, 88);

INSERT INTO Prod VALUES ( 
3055, 'Lotus 123', 'SPSH', 3088, 399.95, 0, '18-OCT-1990' ,26, 12);

INSERT INTO Prod VALUES ( 
3088, 'Macintosh', 'OS', NULL, 149.95, NULL, '12-DEC-1989' ,41, 142);

INSERT INTO Prod VALUES ( 
1108, 'Finance', 'BUS', 4186, 99.95, NULL, '22-APR-1991' ,82, 16);

INSERT INTO Prod VALUES ( 
9167, 'Lotus 123', 'SPSH', 7224, 399.95, 35, '26-FEB-1989' ,26, 71);

INSERT INTO Prod VALUES ( 
4925, 'Paradox', 'DBMS', 7224, 345, 25, '21-SEP-1989' ,55, 64);

INSERT INTO Prod VALUES ( 
1067, 'Finance', 'BUS', 9167, 99.95, NULL, '07-MAR-1989' ,82, 0);

INSERT INTO Prod VALUES ( 
6482, 'BusPlan', 'BUS', 4186, 54.5, 10, '05-JAN-1991' ,82, 41);

INSERT INTO Prod VALUES ( 
7190, 'BusPlan', 'BUS', 9167, 54.5, 10, '14-FEB-1989' ,82, NULL);

INSERT INTO Prod VALUES ( 
6888, 'BusPlan', 'BUS', 3055, 54.5, 0, '14-FEB-1989' ,82, 26);

INSERT INTO Prod VALUES ( 
3981, 'SQL*Report', 'DBMS', 5476, 149.5, 0, '22-SEP-1990' ,58, 12);

INSERT INTO Prod VALUES ( 
9482, 'Quattro', 'SPSH', 7224, 199.95, 30, '24-AUG-1990' ,55, 53);

INSERT INTO Prod VALUES ( 
5476, 'Oracle', 'DBMS', 7224, 895, 5, '12-SEP-1990' ,58, 38);

INSERT INTO Prod VALUES ( 
3007, 'Finance', 'BUS', 9482, 99.95, NULL, '06-NOV-1990' ,82, 17);

INSERT INTO Prod VALUES ( 
8120, 'Inventory', 'BUS', 9482, 199.5, 10, '06-NOV-1990' ,82, 0);

INSERT INTO Prod VALUES ( 
1830, 'SQL*Plus', 'DBMS', 5476, 199.5, 5, '06-OCT-1990' ,58, 19);

CREATE TABLE Vend 
( VName CHAR(10), 
VState CHAR(2), 
VendNo NUMBER(2) NOT NULL, 
Acct CHAR(5), 
PRIMARY KEY (VendNo));

INSERT INTO Vend VALUES ( 
'Apple', 'CA', 41, 'COD');

INSERT INTO Vend VALUES ( 
'Oracle', 'CA', 58, '30');

INSERT INTO Vend VALUES ( 
'Lotus', 'UT', 26, '30');

INSERT INTO Vend VALUES ( 
'Microsoft', 'WA', 12, '10');

INSERT INTO Vend VALUES ( 
'Acme', 'UT', 82, 'COD');

INSERT INTO Vend VALUES ( 
'Borland', 'CA', 55, '30');

INSERT INTO Vend VALUES ( 
'Ace', 'OR', 67, '30');

COMMIT;

SELECT e.EMPNO AS "Employee Number",  
       e.ENAME AS "Employee Name",  
       e.HIREDATE AS "Hiredate",  
       m.ENAME AS "Mgr Name" 
FROM EMP e 
JOIN EMP m ON e.MGR = m.EMPNO 
WHERE m.ENAME LIKE 'K%'  
   OR m.ENAME LIKE 'M%'  
   OR m.ENAME LIKE 'S%';

SELECT e.EMPNO AS "Employee Number",  
       e.ENAME AS "Employee Name",  
       e.HIREDATE AS "Hiredate",  
       m.ENAME AS "Mgr Name" 
FROM EMP e 
JOIN EMP m ON e.MGR = m.EMPNO 
WHERE m.ENAME LIKE 'K%'  
   OR m.ENAME LIKE 'M%'  
   OR m.ENAME LIKE 'S%';

SELECT e1.ENAME AS "Employee Name",  
       e1.DEPTNO AS "Department Number",  
       d.DNAME AS "Department Name",  
       e2.ENAME AS "Colleague Name" 
FROM EMP e1 
JOIN EMP e2 ON e1.DEPTNO = e2.DEPTNO 
JOIN DEPT d ON e1.DEPTNO = d.DEPTNO 
WHERE e1.EMPNO = :given_employee_number;

SELECT d.DNAME AS "Department Name",  
       d.LOC AS "Location" 
FROM EMP e 
JOIN DEPT d ON e.DEPTNO = d.DEPTNO 
WHERE e.JOB = 'CLERK';

INSERT INTO DEPT (DEPTNO, DNAME, LOC) 
VALUES (50, 'TRAINING', 'San Francisco');

SELECT e.EMPNO AS "Emp Number",  
       e.ENAME AS "Emp Name",  
       d.DNAME AS "Dept Name",  
       d.LOC AS "Dept Location" 
FROM EMP e 
JOIN DEPT d ON e.DEPTNO = d.DEPTNO 
WHERE e.DEPTNO IN (20, 50);

SELECT e.EMPNO AS "Employee Number",  
       e.ENAME AS "Employee Name",  
       e.HIREDATE AS "Hiredate",  
       m.ENAME AS "Mgr Name" 
FROM EMP e 
JOIN EMP m ON e.MGR = m.EMPNO 
WHERE m.ENAME LIKE 'K%'  
   OR m.ENAME LIKE 'M%'  
   OR m.ENAME LIKE 'S%';

SELECT e1.ENAME AS "Employee Name",  
       e1.DEPTNO AS "Department Number",  
       d.DNAME AS "Department Name",  
       e2.ENAME AS "Colleague Name" 
FROM EMP e1 
JOIN EMP e2 ON e1.DEPTNO = e2.DEPTNO 
JOIN DEPT d ON e1.DEPTNO = d.DEPTNO 
WHERE e1.EMPNO = :given_employee_number;

SELECT d.DNAME AS "Department Name",  
       d.LOC AS "Location" 
FROM EMP e 
JOIN DEPT d ON e.DEPTNO = d.DEPTNO 
WHERE e.JOB = 'CLERK';

INSERT INTO DEPT (DEPTNO, DNAME, LOC) 
VALUES (50, 'TRAINING', 'San Francisco');

SELECT e.EMPNO AS "Emp Number",  
       e.ENAME AS "Emp Name",  
       d.DNAME AS "Dept Name",  
       d.LOC AS "Dept Location" 
FROM EMP e 
JOIN DEPT d ON e.DEPTNO = d.DEPTNO 
WHERE e.DEPTNO IN (20, 50);

CREATE TABLE DEPT ( 
    DEPTNO NUMBER(2) NOT NULL, 
    DNAME CHAR(14), 
    LOC CHAR(13), 
    CONSTRAINT DEPT_PRIMARY_KEY PRIMARY KEY (DEPTNO) 
);

CREATE TABLE EMP2 ( 
    EMPNO NUMBER(4) NOT NULL, 
    ENAME CHAR(10), 
    JOB CHAR(9), 
    MGR NUMBER(4) CONSTRAINT EMP2_SELF_KEY REFERENCES EMP2 (EMPNO), 
    HIREDATE DATE, 
    SAL NUMBER(7,2), 
    COMM NUMBER(7,2), 
    DEPTNO NUMBER(2), 
    CONSTRAINT EMP2_FOREIGN_KEY FOREIGN KEY (DEPTNO) REFERENCES DEPT (DEPTNO), 
    CONSTRAINT EMP2_PRIM_KEY PRIMARY KEY (EMPNO) 
);

INSERT INTO EMP2 VALUES (7839,'KING','PRESIDENT',NULL,'17-NOV-1981',5000,NULL,10);

INSERT INTO EMP2 VALUES (7698,'BLAKE','MANAGER',7839,'1-MAY-1981',2850,NULL,30);

COMMIT;

SELECT e.EMPNO AS "Employee Number",  
       e.ENAME AS "Employee Name",  
       e.HIREDATE AS "Hiredate",  
       m.ENAME AS "Mgr Name" 
FROM EMP e 
JOIN EMP m ON e.MGR = m.EMPNO 
WHERE m.ENAME LIKE 'K%'  
   OR m.ENAME LIKE 'M%'  
   OR m.ENAME LIKE 'S%';

SELECT e1.ENAME AS "Employee Name",  
       e1.DEPTNO AS "Department Number",  
       d.DNAME AS "Department Name",  
       e2.ENAME AS "Colleague Name" 
FROM EMP e1 
JOIN EMP e2 ON e1.DEPTNO = e2.DEPTNO 
JOIN DEPT d ON e1.DEPTNO = d.DEPTNO 
WHERE e1.EMPNO = :given_employee_number;

SELECT d.DNAME AS "Department Name",  
       d.LOC AS "Location" 
FROM EMP e 
JOIN DEPT d ON e.DEPTNO = d.DEPTNO 
WHERE e.JOB = 'CLERK';

INSERT INTO DEPT (DEPTNO, DNAME, LOC) 
VALUES (50, 'TRAINING', 'San Francisco');

SELECT e.EMPNO AS "Emp Number",  
       e.ENAME AS "Emp Name",  
       d.DNAME AS "Dept Name",  
       d.LOC AS "Dept Location" 
FROM EMP e 
JOIN DEPT d ON e.DEPTNO = d.DEPTNO 
WHERE e.DEPTNO IN (20, 50);

CREATE TABLE DEPT ( 
    DEPTNO NUMBER(2) NOT NULL, 
    DNAME CHAR(14), 
    LOC CHAR(13), 
    CONSTRAINT DEPT_PRIMARY_KEY PRIMARY KEY (DEPTNO) 
);

CREATE TABLE EMP2 ( 
    EMPNO NUMBER(4) NOT NULL, 
    ENAME CHAR(10), 
    JOB CHAR(9), 
    MGR NUMBER(4) CONSTRAINT EMP2_SELF_KEY REFERENCES EMP2 (EMPNO), 
    HIREDATE DATE, 
    SAL NUMBER(7,2), 
    COMM NUMBER(7,2), 
    DEPTNO NUMBER(2), 
    CONSTRAINT EMP2_FOREIGN_KEY FOREIGN KEY (DEPTNO) REFERENCES DEPT (DEPTNO), 
    CONSTRAINT EMP2_PRIM_KEY PRIMARY KEY (EMPNO) 
);

INSERT INTO EMP2 VALUES (7839,'KING','PRESIDENT',NULL,'17-NOV-1981',5000,NULL,10);

INSERT INTO EMP2 VALUES (7698,'BLAKE','MANAGER',7839,'1-MAY-1981',2850,NULL,30);

COMMIT;

INSERT INTO EMP2 (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) 
VALUES (8001, 'NEWEMP', 'ANALYST', 7839, '15-OCT-2024', 3500, NULL, NULL);

SELECT e.EMPNO AS "Employee Number",  
       e.ENAME AS "Employee Name",  
       e.HIREDATE AS "Hiredate",  
       m.ENAME AS "Mgr Name" 
FROM EMP2 e 
JOIN EMP2 m ON e.MGR = m.EMPNO 
WHERE m.ENAME LIKE 'K%'  
   OR m.ENAME LIKE 'M%'  
   OR m.ENAME LIKE 'S%';

SELECT e1.ENAME AS "Employee Name",  
       e1.DEPTNO AS "Department Number",  
       d.DNAME AS "Department Name",  
       e2.ENAME AS "Colleague Name" 
FROM EMP2 e1 
JOIN EMP2 e2 ON e1.DEPTNO = e2.DEPTNO 
JOIN DEPT d ON e1.DEPTNO = d.DEPTNO 
WHERE e1.EMPNO = :given_employee_number;

SELECT d.DNAME AS "Department Name",  
       d.LOC AS "Location" 
FROM EMP2 e 
JOIN DEPT d ON e.DEPTNO = d.DEPTNO 
WHERE e.JOB = 'CLERK';

INSERT INTO DEPT (DEPTNO, DNAME, LOC) 
VALUES (50, 'TRAINING', 'San Francisco');

SELECT e.EMPNO AS "Emp Number",  
       e.ENAME AS "Emp Name",  
       d.DNAME AS "Dept Name",  
       d.LOC AS "Dept Location" 
FROM EMP2 e 
JOIN DEPT d ON e.DEPTNO = d.DEPTNO 
WHERE e.DEPTNO IN (20, 50);

INSERT INTO EMP2 (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) 
VALUES (8001, 'NEWEMP', 'ANALYST', 7839, '15-OCT-2024', 3500, NULL, NULL);

SELECT e.EMPNO AS "Employee Number",  
       e.ENAME AS "Employee Name",  
       e.JOB AS "Job",  
       e.HIREDATE AS "Hiredate",  
       e.SAL AS "Salary",  
       e.COMM AS "Commission",  
       d.DNAME AS "Department Name",  
       d.LOC AS "Location" 
FROM EMP2 e 
LEFT JOIN DEPT d ON e.DEPTNO = d.DEPTNO;

SELECT e.EMPNO AS "Employee Number",  
       e.ENAME AS "Employee Name",  
       e.HIREDATE AS "Hiredate",  
       m.ENAME AS "Mgr Name" 
FROM EMP2 e 
JOIN EMP2 m ON e.MGR = m.EMPNO 
WHERE m.ENAME LIKE 'K%'  
   OR m.ENAME LIKE 'M%'  
   OR m.ENAME LIKE 'S%';

SELECT e1.ENAME AS "Employee Name",  
       e1.DEPTNO AS "Department Number",  
       d.DNAME AS "Department Name",  
       e2.ENAME AS "Colleague Name" 
FROM EMP2 e1 
JOIN EMP2 e2 ON e1.DEPTNO = e2.DEPTNO 
JOIN DEPT d ON e1.DEPTNO = d.DEPTNO 
WHERE e1.EMPNO = 7839;

SELECT d.DNAME AS "Department Name",  
       d.LOC AS "Location" 
FROM EMP2 e 
JOIN DEPT d ON e.DEPTNO = d.DEPTNO 
WHERE e.JOB = 'CLERK';

INSERT INTO DEPT (DEPTNO, DNAME, LOC) 
VALUES (51, 'TRAINING', 'San Francisco');

SELECT e.EMPNO AS "Emp Number",  
       e.ENAME AS "Emp Name",  
       d.DNAME AS "Dept Name",  
       d.LOC AS "Dept Location" 
FROM EMP2 e 
JOIN DEPT d ON e.DEPTNO = d.DEPTNO 
WHERE e.DEPTNO IN (20, 50);

INSERT INTO EMP2 (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) 
VALUES (8001, 'NEWEMP', 'ANALYST', 7839, '15-OCT-2024', 3500, NULL, NULL);

SELECT e.EMPNO AS "Employee Number",  
       e.ENAME AS "Employee Name",  
       e.JOB AS "Job",  
       e.HIREDATE AS "Hiredate",  
       e.SAL AS "Salary",  
       e.COMM AS "Commission",  
       d.DNAME AS "Department Name",  
       d.LOC AS "Location" 
FROM EMP2 e 
LEFT JOIN DEPT d ON e.DEPTNO = d.DEPTNO;

SELECT e.EMPNO AS "Employee Number",  
       e.ENAME AS "Employee Name",  
       e.HIREDATE AS "Hiredate",  
       m.ENAME AS "Mgr Name" 
FROM EMP2 e 
JOIN EMP2 m ON e.MGR = m.EMPNO 
WHERE m.ENAME LIKE 'K%'  
   OR m.ENAME LIKE 'M%'  
   OR m.ENAME LIKE 'S%';

SELECT e1.ENAME AS "Employee Name",  
       e1.DEPTNO AS "Department Number",  
       d.DNAME AS "Department Name",  
       e2.ENAME AS "Colleague Name" 
FROM EMP2 e1 
JOIN EMP2 e2 ON e1.DEPTNO = e2.DEPTNO 
JOIN DEPT d ON e1.DEPTNO = d.DEPTNO 
WHERE e1.EMPNO = 7839;

SELECT d.DNAME AS "Department Name",  
       d.LOC AS "Location" 
FROM EMP2 e 
JOIN DEPT d ON e.DEPTNO = d.DEPTNO 
WHERE e.JOB = 'CLERK';

INSERT INTO DEPT (DEPTNO, DNAME, LOC) 
VALUES (51, 'TRAINING', 'San Francisco');

SELECT e.EMPNO AS "Emp Number",  
       e.ENAME AS "Emp Name",  
       d.DNAME AS "Dept Name",  
       d.LOC AS "Dept Location" 
FROM EMP2 e 
JOIN DEPT d ON e.DEPTNO = d.DEPTNO 
WHERE e.DEPTNO IN (20, 50);

INSERT INTO EMP2 (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) 
VALUES (8002, 'NEWEMP', 'ANALYST', 7839, '15-OCT-2024', 3500, NULL, NULL);

SELECT e.EMPNO AS "Employee Number",  
       e.ENAME AS "Employee Name",  
       e.JOB AS "Job",  
       e.HIREDATE AS "Hiredate",  
       e.SAL AS "Salary",  
       e.COMM AS "Commission",  
       d.DNAME AS "Department Name",  
       d.LOC AS "Location" 
FROM EMP2 e 
LEFT JOIN DEPT d ON e.DEPTNO = d.DEPTNO;

SELECT e.EMPNO AS "Employee Number",  
       e.ENAME AS "Employee Name",  
       e.HIREDATE AS "Hiredate",  
       m.ENAME AS "Mgr Name" 
FROM EMP e 
JOIN EMP m ON e.MGR = m.EMPNO 
WHERE m.ENAME LIKE 'K%'  
   OR m.ENAME LIKE 'M%'  
   OR m.ENAME LIKE 'S%';

SELECT e1.ENAME AS "Employee Name",  
       e1.DEPTNO AS "Department Number",  
       d.DNAME AS "Department Name",  
       e2.ENAME AS "Colleague Name" 
FROM EMP e1 
JOIN EMP e2 ON e1.DEPTNO = e2.DEPTNO 
JOIN DEPT d ON e1.DEPTNO = d.DEPTNO 
WHERE e1.EMPNO = 7839;

SELECT d.DNAME AS "Department Name",  
       d.LOC AS "Location" 
FROM EMP e 
JOIN DEPT d ON e.DEPTNO = d.DEPTNO 
WHERE e.JOB = 'CLERK';

INSERT INTO DEPT (DEPTNO, DNAME, LOC) 
VALUES (50, 'TRAINING', 'San Francisco');

SELECT e.EMPNO AS "Employee Number",  
       e.ENAME AS "Employee Name",  
       d.DNAME AS "Department Name",  
       d.LOC AS "Location" 
FROM EMP e 
JOIN DEPT d ON e.DEPTNO = d.DEPTNO 
WHERE e.DEPTNO IN (20, 50);

INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) 
VALUES (8001, 'NEWEMP', 'ANALYST', 7839, '15-OCT-2024', 3500, NULL, NULL);

SELECT e.EMPNO AS "Employee Number",  
       e.ENAME AS "Employee Name",  
       e.JOB AS "Job",  
       e.HIREDATE AS "Hiredate",  
       e.SAL AS "Salary",  
       d.DNAME AS 
 
 
;

SELECT e.EMPNO AS "Employee Number",  
       e.ENAME AS "Employee Name",  
       e.HIREDATE AS "Hiredate",  
       m.ENAME AS "Mgr Name" 
FROM EMP e 
JOIN EMP m ON e.MGR = m.EMPNO 
WHERE m.ENAME LIKE 'K%'  
   OR m.ENAME LIKE 'M%'  
   OR m.ENAME LIKE 'S%';

SELECT e1.ENAME AS "Employee Name",  
       e1.DEPTNO AS "Department Number",  
       d.DNAME AS "Department Name",  
       e2.ENAME AS "Colleague Name" 
FROM EMP e1 
JOIN EMP e2 ON e1.DEPTNO = e2.DEPTNO 
JOIN DEPT d ON e1.DEPTNO = d.DEPTNO 
WHERE e1.EMPNO = 7839;

SELECT d.DNAME AS "Department Name",  
       d.LOC AS "Location" 
FROM EMP e 
JOIN DEPT d ON e.DEPTNO = d.DEPTNO 
WHERE e.JOB = 'CLERK';

INSERT INTO DEPT (DEPTNO, DNAME, LOC) 
VALUES (50, 'TRAINING', 'San Francisco');

SELECT e.EMPNO AS "Employee Number",  
       e.ENAME AS "Employee Name",  
       d.DNAME AS "Department Name",  
       d.LOC AS "Location" 
FROM EMP e 
JOIN DEPT d ON e.DEPTNO = d.DEPTNO 
WHERE e.DEPTNO IN (20, 50);

ALTER TABLE EMP MODIFY DEPTNO NULL;

INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) 
VALUES (8002, 'NEWEMP', 'ANALYST', 7839, '15-OCT-2024', 3500, NULL, 10);

SELECT e.EMPNO AS "Employee Number",  
       e.ENAME AS "Employee Name",  
       e.JOB AS "Job",  
       e.HIREDATE AS "Hiredate",  
       e.SAL AS "Salary",  
       e.COMM AS "Commission",  
       d.DNAME AS "Department Name",  
       d.LOC AS "Location" 
FROM EMP e 
LEFT JOIN DEPT d ON e.DEPTNO = d.DEPTNO;

SELECT e.EMPNO AS "Employee Number",  
       e.ENAME AS "Employee Name",  
       e.HIREDATE AS "Hiredate",  
       m.ENAME AS "Mgr Name" 
FROM EMP e 
JOIN EMP m ON e.MGR = m.EMPNO 
WHERE m.ENAME LIKE 'K%'  
   OR m.ENAME LIKE 'M%'  
   OR m.ENAME LIKE 'S%';

SELECT e1.ENAME AS "Employee Name",  
       e1.DEPTNO AS "Department Number",  
       d.DNAME AS "Department Name",  
       e2.ENAME AS "Colleague Name" 
FROM EMP e1 
JOIN EMP e2 ON e1.DEPTNO = e2.DEPTNO 
JOIN DEPT d ON e1.DEPTNO = d.DEPTNO 
WHERE e1.EMPNO = 7839;

SELECT d.DNAME AS "Department Name",  
       d.LOC AS "Location" 
FROM EMP e 
JOIN DEPT d ON e.DEPTNO = d.DEPTNO 
WHERE e.JOB = 'CLERK';

INSERT INTO DEPT (DEPTNO, DNAME, LOC) 
VALUES (50, 'TRAINING', 'San Francisco');

SELECT e.EMPNO AS "Employee Number",  
       e.ENAME AS "Employee Name",  
       d.DNAME AS "Department Name",  
       d.LOC AS "Location" 
FROM EMP e 
JOIN DEPT d ON e.DEPTNO = d.DEPTNO 
WHERE e.DEPTNO IN (20, 50);

ALTER TABLE EMP MODIFY DEPTNO NULL;

INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) 
VALUES (8002, 'NEWEMP', 'ANALYST', 7839, '15-OCT-2024', 3500, NULL, 10);

SELECT e.EMPNO AS "Employee Number",  
       e.ENAME AS "Employee Name",  
       e.JOB AS "Job",  
       e.HIREDATE AS "Hiredate",  
       e.SAL AS "Salary",  
       e.COMM AS "Commission",  
       d.DNAME AS "Department Name",  
       d.LOC AS "Location" 
FROM EMP e 
LEFT JOIN DEPT d ON e.DEPTNO = d.DEPTNO;

SELECT e.EMPNO AS "Employee Number",  
       e.ENAME AS "Employee Name",  
       e.HIREDATE AS "Hiredate",  
       m.ENAME AS "Mgr Name" 
FROM EMP e 
JOIN EMP m ON e.MGR = m.EMPNO 
WHERE m.ENAME LIKE 'K%'  
   OR m.ENAME LIKE 'M%'  
   OR m.ENAME LIKE 'S%';

SELECT e1.ENAME AS "Employee Name",  
       e1.DEPTNO AS "Department Number",  
       d.DNAME AS "Department Name",  
       e2.ENAME AS "Colleague Name" 
FROM EMP e1 
JOIN EMP e2 ON e1.DEPTNO = e2.DEPTNO 
JOIN DEPT d ON e1.DEPTNO = d.DEPTNO 
WHERE e1.EMPNO = 7839;

SELECT d.DNAME AS "Department Name",  
       d.LOC AS "Location" 
FROM EMP e 
JOIN DEPT d ON e.DEPTNO = d.DEPTNO 
WHERE e.JOB = 'CLERK';

INSERT INTO DEPT (DEPTNO, DNAME, LOC) 
VALUES (50, 'TRAINING', 'San Francisco');

SELECT e.EMPNO AS "Employee Number",  
       e.ENAME AS "Employee Name",  
       d.DNAME AS "Department Name",  
       d.LOC AS "Location" 
FROM EMP e 
JOIN DEPT d ON e.DEPTNO = d.DEPTNO 
WHERE e.DEPTNO IN (20, 50);

ALTER TABLE EMP MODIFY DEPTNO NULL;

INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) 
VALUES (8002, 'NEWEMP', 'ANALYST', 7839, '15-OCT-2024', 3500, NULL, 10);

SELECT e.EMPNO AS "Employee Number",  
       e.ENAME AS "Employee Name",  
       e.JOB AS "Job",  
       e.HIREDATE AS "Hiredate",  
       e.SAL AS "Salary",  
       e.COMM AS "Commission",  
       d.DNAME AS "Department Name",  
       d.LOC AS "Location" 
FROM EMP e 
LEFT JOIN DEPT d ON e.DEPTNO = d.DEPTNO;

SELECT e.EMPNO AS "Employee Number",  
       e.ENAME AS "Employee Name",  
       e.HIREDATE AS "Hiredate",  
       m.ENAME AS "Mgr Name" 
FROM EMP e 
JOIN EMP m ON e.MGR = m.EMPNO 
WHERE m.ENAME LIKE 'K%'  
   OR m.ENAME LIKE 'M%'  
   OR m.ENAME LIKE 'S%';

SELECT e1.ENAME AS "Employee Name",  
       e1.DEPTNO AS "Department Number",  
       d.DNAME AS "Department Name",  
       e2.ENAME AS "Colleague Name" 
FROM EMP e1 
JOIN EMP e2 ON e1.DEPTNO = e2.DEPTNO 
JOIN DEPT d ON e1.DEPTNO = d.DEPTNO 
WHERE e1.EMPNO = 7839;

SELECT d.DNAME AS "Department Name",  
       d.LOC AS "Location" 
FROM EMP e 
JOIN DEPT d ON e.DEPTNO = d.DEPTNO 
WHERE e.JOB = 'CLERK';

INSERT INTO DEPT (DEPTNO, DNAME, LOC) 
VALUES (50, 'TRAINING', 'San Francisco');

SELECT e.EMPNO AS "Employee Number",  
       e.ENAME AS "Employee Name",  
       d.DNAME AS "Department Name",  
       d.LOC AS "Location" 
FROM EMP e 
JOIN DEPT d ON e.DEPTNO = d.DEPTNO 
WHERE e.DEPTNO IN (20, 50);

ALTER TABLE EMP MODIFY DEPTNO NULL;

INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) 
VALUES (8002, 'NEWEMP', 'ANALYST', 7839, '15-OCT-2024', 3500, NULL, 10);

SELECT e.EMPNO AS "Employee Number",  
       e.ENAME AS "Employee Name",  
       e.JOB AS "Job",  
       e.HIREDATE AS "Hiredate",  
       e.SAL AS "Salary",  
       e.COMM AS "Commission",  
       d.DNAME AS "Department Name",  
       d.LOC AS "Location" 
FROM EMP e 
LEFT JOIN DEPT d ON e.DEPTNO = d.DEPTNO;

INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) 
VALUES (8003, 'NEWEMP', 'ANALYST', 7839, '15-OCT-2024', 3500, NULL, 10);

SELECT e.EMPNO AS "Employee Number",  
       e.ENAME AS "Employee Name",  
       e.HIREDATE AS "Hiredate",  
       m.ENAME AS "Mgr Name" 
FROM EMP e 
JOIN EMP m ON e.MGR = m.EMPNO 
WHERE m.ENAME LIKE 'K%'  
   OR m.ENAME LIKE 'M%'  
   OR m.ENAME LIKE 'S%';

SELECT e1.ENAME AS "Employee Name",  
       e1.DEPTNO AS "Department Number",  
       d.DNAME AS "Department Name",  
       e2.ENAME AS "Colleague Name" 
FROM EMP e1 
JOIN EMP e2 ON e1.DEPTNO = e2.DEPTNO 
JOIN DEPT d ON e1.DEPTNO = d.DEPTNO 
WHERE e1.EMPNO = 7839;

SELECT d.DNAME AS "Department Name",  
       d.LOC AS "Location" 
FROM EMP e 
JOIN DEPT d ON e.DEPTNO = d.DEPTNO 
WHERE e.JOB = 'CLERK';

INSERT INTO DEPT (DEPTNO, DNAME, LOC) 
VALUES (51, 'TRAINING', 'San Francisco');

SELECT e.EMPNO AS "Employee Number",  
       e.ENAME AS "Employee Name",  
       d.DNAME AS "Department Name",  
       d.LOC AS "Location" 
FROM EMP e 
JOIN DEPT d ON e.DEPTNO = d.DEPTNO 
WHERE e.DEPTNO IN (20, 50);

ALTER TABLE EMP MODIFY DEPTNO NULL;

INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) 
VALUES (8003, 'NEWEMP', 'ANALYST', 7839, '15-OCT-2024', 3500, NULL, 10);

SELECT e.EMPNO AS "Employee Number",  
       e.ENAME AS "Employee Name",  
       e.JOB AS "Job",  
       e.HIREDATE AS "Hiredate",  
       e.SAL AS "Salary",  
       e.COMM AS "Commission",  
       d.DNAME AS "Department Name",  
       d.LOC AS "Location" 
FROM EMP e 
LEFT JOIN DEPT d ON e.DEPTNO = d.DEPTNO;

SELECT  
    EMP.EMPNO AS "Employee Number",  
    EMP.ENAME AS "Employee Name",  
    EMP.HIREDATE AS "Hiredate",  
    MGR.ENAME AS "Mgr Name" 
FROM  
    EMP EMP 
    JOIN EMP MGR ON EMP.MGR = MGR.EMPNO 
WHERE  
    MGR.ENAME LIKE 'K%'  
    OR MGR.ENAME LIKE 'M%'  
    OR MGR.ENAME LIKE 'S%';

SELECT  
    E1.ENAME AS "Employee Name",  
    E1.DEPTNO AS "Department Number",  
    D.DNAME AS "Department Name",  
    E2.ENAME AS "Colleague Name" 
FROM  
    EMP E1 
    JOIN DEPT D ON E1.DEPTNO = D.DEPTNO 
    JOIN EMP E2 ON E1.DEPTNO = E2.DEPTNO 
WHERE  
    E1.ENAME = 'GIVEN_EMPLOYEE_NAME';

SELECT  
    D.DNAME AS "Department Name",  
    D.LOC AS "Location" 
FROM  
    EMP E 
    JOIN DEPT D ON E.DEPTNO = D.DEPTNO 
WHERE  
    E.JOB = 'CLERK';

INSERT INTO DEPT (DEPTNO, DNAME, LOC)  
VALUES (50, 'TRAINING', 'SAN FRANCISCO');

SELECT  
    E.EMPNO AS "Emp Number",  
    E.ENAME AS "Emp Name",  
    D.DNAME AS "Dept Name",  
    D.LOC AS "Dept Location" 
FROM  
    EMP E 
    JOIN DEPT D ON E.DEPTNO = D.DEPTNO 
WHERE  
    E.DEPTNO IN (20, 50);

INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)  
VALUES (NEW_EMPNO, 'NEW_EMPLOYEE', 'NEW_JOB', MANAGER_EMPNO, 'NEW_HIRE_DATE', SALARY, COMMISSION, NULL);

SELECT  
    E.EMPNO AS "Emp Number",  
    E.ENAME AS "Emp Name",  
    D.DNAME AS "Dept Name",  
    D.LOC AS "Dept Location" 
FROM  
    EMP E 
    LEFT JOIN DEPT D ON E.DEPTNO = D.DEPTNO;

SELECT  
    EMP.EMPNO AS "Employee Number",  
    EMP.ENAME AS "Employee Name",  
    EMP.HIREDATE AS "Hiredate",  
    MGR.ENAME AS "Mgr Name" 
FROM  
    EMP EMP 
    JOIN EMP MGR ON EMP.MGR = MGR.EMPNO 
WHERE  
    MGR.ENAME LIKE 'K%'  
    OR MGR.ENAME LIKE 'M%'  
    OR MGR.ENAME LIKE 'S%';

SELECT  
    E1.ENAME AS "Employee Name",  
    E1.DEPTNO AS "Department Number",  
    D.DNAME AS "Department Name",  
    E2.ENAME AS "Colleague Name" 
FROM  
    EMP E1 
    JOIN DEPT D ON E1.DEPTNO = D.DEPTNO 
    JOIN EMP E2 ON E1.DEPTNO = E2.DEPTNO 
WHERE  
    E1.ENAME = 'GIVEN_EMPLOYEE_NAME';

SELECT  
    D.DNAME AS "Department Name",  
    D.LOC AS "Location" 
FROM  
    EMP E 
    JOIN DEPT D ON E.DEPTNO = D.DEPTNO 
WHERE  
    E.JOB = 'CLERK';

INSERT INTO DEPT (DEPTNO, DNAME, LOC)  
VALUES (50, 'TRAINING', 'SAN FRANCISCO');

SELECT  
    E.EMPNO AS "Emp Number",  
    E.ENAME AS "Emp Name",  
    D.DNAME AS "Dept Name",  
    D.LOC AS "Dept Location" 
FROM  
    EMP E 
    JOIN DEPT D ON E.DEPTNO = D.DEPTNO 
WHERE  
    E.DEPTNO IN (20, 50);

INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)  
VALUES (NEW_EMPNO, 'NEW_EMPLOYEE', 'NEW_JOB', MANAGER_EMPNO, 'NEW_HIRE_DATE', SALARY, COMMISSION, NULL);

SELECT  
    E.EMPNO AS "Emp Number",  
    E.ENAME AS "Emp Name",  
    D.DNAME AS "Dept Name",  
    D.LOC AS "Dept Location" 
FROM  
    EMP E 
    LEFT JOIN DEPT D ON E.DEPTNO = D.DEPTNO;

SELECT * FROM DEPT WHERE DEPTNO = 50;

SELECT  
    EMP.EMPNO AS "Employee Number",  
    EMP.ENAME AS "Employee Name",  
    EMP.HIREDATE AS "Hiredate",  
    MGR.ENAME AS "Mgr Name" 
FROM  
    EMP EMP 
    JOIN EMP MGR ON EMP.MGR = MGR.EMPNO 
WHERE  
    MGR.ENAME LIKE 'K%'  
    OR MGR.ENAME LIKE 'M%'  
    OR MGR.ENAME LIKE 'S%';

SELECT  
    E1.ENAME AS "Employee Name",  
    E1.DEPTNO AS "Department Number",  
    D.DNAME AS "Department Name",  
    E2.ENAME AS "Colleague Name" 
FROM  
    EMP E1 
    JOIN DEPT D ON E1.DEPTNO = D.DEPTNO 
    JOIN EMP E2 ON E1.DEPTNO = E2.DEPTNO 
WHERE  
    E1.ENAME = 'GIVEN_EMPLOYEE_NAME';

SELECT  
    D.DNAME AS "Department Name",  
    D.LOC AS "Location" 
FROM  
    EMP E 
    JOIN DEPT D ON E.DEPTNO = D.DEPTNO 
WHERE  
    E.JOB = 'CLERK';

INSERT INTO DEPT (DEPTNO, DNAME, LOC)  
VALUES (50, 'TRAINING', 'SAN FRANCISCO');

SELECT  
    E.EMPNO AS "Emp Number",  
    E.ENAME AS "Emp Name",  
    D.DNAME AS "Dept Name",  
    D.LOC AS "Dept Location" 
FROM  
    EMP E 
    JOIN DEPT D ON E.DEPTNO = D.DEPTNO 
WHERE  
    E.DEPTNO IN (20, 50);

INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)  
VALUES (NEW_EMPNO, 'NEW_EMPLOYEE', 'NEW_JOB', MANAGER_EMPNO, 'NEW_HIRE_DATE', SALARY, COMMISSION, NULL);

SELECT  
    E.EMPNO AS "Emp Number",  
    E.ENAME AS "Emp Name",  
    D.DNAME AS "Dept Name",  
    D.LOC AS "Dept Location" 
FROM  
    EMP E 
    LEFT JOIN DEPT D ON E.DEPTNO = D.DEPTNO;

DELETE FROM DEPT WHERE DEPTNO = 50;

SELECT  
    EMP.EMPNO AS "Employee Number",  
    EMP.ENAME AS "Employee Name",  
    EMP.HIREDATE AS "Hiredate",  
    MGR.ENAME AS "Mgr Name" 
FROM  
    EMP EMP 
    JOIN EMP MGR ON EMP.MGR = MGR.EMPNO 
WHERE  
    MGR.ENAME LIKE 'K%'  
    OR MGR.ENAME LIKE 'M%'  
    OR MGR.ENAME LIKE 'S%';

SELECT  
    E1.ENAME AS "Employee Name",  
    E1.DEPTNO AS "Department Number",  
    D.DNAME AS "Department Name",  
    E2.ENAME AS "Colleague Name" 
FROM  
    EMP E1 
    JOIN DEPT D ON E1.DEPTNO = D.DEPTNO 
    JOIN EMP E2 ON E1.DEPTNO = E2.DEPTNO 
WHERE  
    E1.ENAME = 'GIVEN_EMPLOYEE_NAME';

SELECT  
    D.DNAME AS "Department Name",  
    D.LOC AS "Location" 
FROM  
    EMP E 
    JOIN DEPT D ON E.DEPTNO = D.DEPTNO 
WHERE  
    E.JOB = 'CLERK';

INSERT INTO DEPT (DEPTNO, DNAME, LOC)  
VALUES (60, 'TRAINING', 'SAN FRANCISCO');

SELECT  
    E.EMPNO AS "Emp Number",  
    E.ENAME AS "Emp Name",  
    D.DNAME AS "Dept Name",  
    D.LOC AS "Dept Location" 
FROM  
    EMP E 
    JOIN DEPT D ON E.DEPTNO = D.DEPTNO 
WHERE  
    E.DEPTNO IN (20, 50);

INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)  
VALUES (8003, 'NEWEMP', 'CLERK', 7839, '15-OCT-2024', 1200, NULL, NULL);

SELECT  
    E.EMPNO AS "Emp Number",  
    E.ENAME AS "Emp Name",  
    D.DNAME AS "Dept Name",  
    D.LOC AS "Dept Location" 
FROM  
    EMP E 
    LEFT JOIN DEPT D ON E.DEPTNO = D.DEPTNO;

DELETE FROM DEPT WHERE DEPTNO = 50;

SELECT  
    EMP.EMPNO AS "Employee Number",  
    EMP.ENAME AS "Employee Name",  
    EMP.HIREDATE AS "Hiredate",  
    MGR.ENAME AS "Mgr Name" 
FROM  
    EMP EMP 
    JOIN EMP MGR ON EMP.MGR = MGR.EMPNO 
WHERE  
    MGR.ENAME LIKE 'K%'  
    OR MGR.ENAME LIKE 'M%'  
    OR MGR.ENAME LIKE 'S%';

SELECT  
    E1.ENAME AS "Employee Name",  
    E1.DEPTNO AS "Department Number",  
    D.DNAME AS "Department Name",  
    E2.ENAME AS "Colleague Name" 
FROM  
    EMP E1 
    JOIN DEPT D ON E1.DEPTNO = D.DEPTNO 
    JOIN EMP E2 ON E1.DEPTNO = E2.DEPTNO 
WHERE  
    E1.ENAME = 'GIVEN_EMPLOYEE_NAME';

SELECT  
    D.DNAME AS "Department Name",  
    D.LOC AS "Location" 
FROM  
    EMP E 
    JOIN DEPT D ON E.DEPTNO = D.DEPTNO 
WHERE  
    E.JOB = 'CLERK';

INSERT INTO DEPT (DEPTNO, DNAME, LOC)  
VALUES (60, 'TRAINING', 'SAN FRANCISCO');

SELECT  
    E.EMPNO AS "Emp Number",  
    E.ENAME AS "Emp Name",  
    D.DNAME AS "Dept Name",  
    D.LOC AS "Dept Location" 
FROM  
    EMP E 
    JOIN DEPT D ON E.DEPTNO = D.DEPTNO 
WHERE  
    E.DEPTNO IN (20, 50);

INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)  
VALUES (8004, 'NEWEMP', 'CLERK', 7839, '15-OCT-2024', 1200, NULL, NULL);

SELECT  
    E.EMPNO AS "Emp Number",  
    E.ENAME AS "Emp Name",  
    D.DNAME AS "Dept Name",  
    D.LOC AS "Dept Location" 
FROM  
    EMP E 
    LEFT JOIN DEPT D ON E.DEPTNO = D.DEPTNO;

DELETE FROM DEPT WHERE DEPTNO = 50;

SELECT  
    EMP.EMPNO AS "Employee Number",  
    EMP.ENAME AS "Employee Name",  
    EMP.HIREDATE AS "Hiredate",  
    MGR.ENAME AS "Mgr Name" 
FROM  
    EMP EMP 
    JOIN EMP MGR ON EMP.MGR = MGR.EMPNO 
WHERE  
    MGR.ENAME LIKE 'K%'  
    OR MGR.ENAME LIKE 'M%'  
    OR MGR.ENAME LIKE 'S%';

SELECT  
    E1.ENAME AS "Employee Name",  
    E1.DEPTNO AS "Department Number",  
    D.DNAME AS "Department Name",  
    E2.ENAME AS "Colleague Name" 
FROM  
    EMP E1 
    JOIN DEPT D ON E1.DEPTNO = D.DEPTNO 
    JOIN EMP E2 ON E1.DEPTNO = E2.DEPTNO 
WHERE  
    E1.ENAME = 'GIVEN_EMPLOYEE_NAME';

SELECT  
    D.DNAME AS "Department Name",  
    D.LOC AS "Location" 
FROM  
    EMP E 
    JOIN DEPT D ON E.DEPTNO = D.DEPTNO 
WHERE  
    E.JOB = 'CLERK';

INSERT INTO DEPT (DEPTNO, DNAME, LOC)  
VALUES (60, 'TRAINING', 'SAN FRANCISCO');

SELECT  
    E.EMPNO AS "Emp Number",  
    E.ENAME AS "Emp Name",  
    D.DNAME AS "Dept Name",  
    D.LOC AS "Dept Location" 
FROM  
    EMP E 
    JOIN DEPT D ON E.DEPTNO = D.DEPTNO 
WHERE  
    E.DEPTNO IN (20, 50);

INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)  
VALUES (8004, 'NEWEMP', 'CLERK', 7839, '15-OCT-2024', 1200, NULL, NULL);

SELECT  
    E.EMPNO AS "Emp Number",  
    E.ENAME AS "Emp Name",  
    D.DNAME AS "Dept Name",  
    D.LOC AS "Dept Location" 
FROM  
    EMP E 
    LEFT JOIN DEPT D ON E.DEPTNO = D.DEPTNO;

SELECT * FROM DEPT WHERE DEPTNO = 50;

SELECT  
    EMP.EMPNO AS "Employee Number",  
    EMP.ENAME AS "Employee Name",  
    EMP.HIREDATE AS "Hiredate",  
    MGR.ENAME AS "Mgr Name" 
FROM  
    EMP EMP 
    JOIN EMP MGR ON EMP.MGR = MGR.EMPNO 
WHERE  
    MGR.ENAME LIKE 'K%'  
    OR MGR.ENAME LIKE 'M%'  
    OR MGR.ENAME LIKE 'S%';

SELECT  
    E1.ENAME AS "Employee Name",  
    E1.DEPTNO AS "Department Number",  
    D.DNAME AS "Department Name",  
    E2.ENAME AS "Colleague Name" 
FROM  
    EMP E1 
    JOIN DEPT D ON E1.DEPTNO = D.DEPTNO 
    JOIN EMP E2 ON E1.DEPTNO = E2.DEPTNO 
WHERE  
    E1.ENAME = 'GIVEN_EMPLOYEE_NAME';

SELECT  
    D.DNAME AS "Department Name",  
    D.LOC AS "Location" 
FROM  
    EMP E 
    JOIN DEPT D ON E.DEPTNO = D.DEPTNO 
WHERE  
    E.JOB = 'CLERK';

INSERT INTO DEPT (DEPTNO, DNAME, LOC)  
VALUES (50, 'TRAINING', 'SAN FRANCISCO');

SELECT  
    E.EMPNO AS "Emp Number",  
    E.ENAME AS "Emp Name",  
    D.DNAME AS "Dept Name",  
    D.LOC AS "Dept Location" 
FROM  
    EMP E 
    JOIN DEPT D ON E.DEPTNO = D.DEPTNO 
WHERE  
    E.DEPTNO IN (20, 50);

INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)  
VALUES (8004, 'NEWEMP', 'CLERK', 7839, '15-OCT-2024', 1200, NULL, NULL);

SELECT  
    E.EMPNO AS "Emp Number",  
    E.ENAME AS "Emp Name",  
    D.DNAME AS "Dept Name",  
    D.LOC AS "Dept Location" 
FROM  
    EMP E 
    LEFT JOIN DEPT D ON E.DEPTNO = D.DEPTNO;

SELECT * FROM DEPT WHERE DEPTNO = 50;

SELECT  
    EMP.EMPNO AS "Employee Number",  
    EMP.ENAME AS "Employee Name",  
    EMP.HIREDATE AS "Hiredate",  
    MGR.ENAME AS "Mgr Name" 
FROM  
    EMP EMP 
    JOIN EMP MGR ON EMP.MGR = MGR.EMPNO 
WHERE  
    MGR.ENAME LIKE 'K%'  
    OR MGR.ENAME LIKE 'M%'  
    OR MGR.ENAME LIKE 'S%';

SELECT  
    E1.ENAME AS "Employee Name",  
    E1.DEPTNO AS "Department Number",  
    D.DNAME AS "Department Name",  
    E2.ENAME AS "Colleague Name" 
FROM  
    EMP E1 
    JOIN DEPT D ON E1.DEPTNO = D.DEPTNO 
    JOIN EMP E2 ON E1.DEPTNO = E2.DEPTNO 
WHERE  
    E1.ENAME = 'GIVEN_EMPLOYEE_NAME';

SELECT  
    D.DNAME AS "Department Name",  
    D.LOC AS "Location" 
FROM  
    EMP E 
    JOIN DEPT D ON E.DEPTNO = D.DEPTNO 
WHERE  
    E.JOB = 'CLERK';

INSERT INTO DEPT (DEPTNO, DNAME, LOC)  
VALUES (50, 'TRAINING', 'SAN FRANCISCO');

SELECT  
    E.EMPNO AS "Emp Number",  
    E.ENAME AS "Emp Name",  
    D.DNAME AS "Dept Name",  
    D.LOC AS "Dept Location" 
FROM  
    EMP E 
    JOIN DEPT D ON E.DEPTNO = D.DEPTNO 
WHERE  
    E.DEPTNO IN (20, 50);

INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)  
VALUES (8004, 'NEWEMP', 'CLERK', 7839, '15-OCT-2024', 1200, NULL, NULL);

SELECT  
    E.EMPNO AS "Emp Number",  
    E.ENAME AS "Emp Name",  
    D.DNAME AS "Dept Name",  
    D.LOC AS "Dept Location" 
FROM  
    EMP E 
    LEFT JOIN DEPT D ON E.DEPTNO = D.DEPTNO;

SELECT  
    EMP.EMPNO AS "Employee Number",  
    EMP.ENAME AS "Employee Name",  
    EMP.HIREDATE AS "Hiredate",  
    MGR.ENAME AS "Mgr Name" 
FROM  
    EMP EMP 
    JOIN EMP MGR ON EMP.MGR = MGR.EMPNO 
WHERE  
    MGR.ENAME LIKE 'K%'  
    OR MGR.ENAME LIKE 'M%'  
    OR MGR.ENAME LIKE 'S%';

SELECT  
    E1.ENAME AS "Employee Name",  
    E1.DEPTNO AS "Department Number",  
    D.DNAME AS "Department Name",  
    E2.ENAME AS "Colleague Name" 
FROM  
    EMP E1 
    JOIN DEPT D ON E1.DEPTNO = D.DEPTNO 
    JOIN EMP E2 ON E1.DEPTNO = E2.DEPTNO 
WHERE  
    E1.ENAME = 'GIVEN_EMPLOYEE_NAME';

SELECT  
    D.DNAME AS "Department Name",  
    D.LOC AS "Location" 
FROM  
    EMP E 
    JOIN DEPT D ON E.DEPTNO = D.DEPTNO 
WHERE  
    E.JOB = 'CLERK';

INSERT INTO DEPT (DEPTNO, DNAME, LOC)  
VALUES (50, 'TRAINING', 'SAN FRANCISCO');

SELECT  
    E.EMPNO AS "Emp Number",  
    E.ENAME AS "Emp Name",  
    D.DNAME AS "Dept Name",  
    D.LOC AS "Dept Location" 
FROM  
    EMP E 
    JOIN DEPT D ON E.DEPTNO = D.DEPTNO 
WHERE  
    E.DEPTNO IN (20, 50);

INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)  
VALUES (8004, 'NEWEMP', 'CLERK', 7839, '15-OCT-2024', 1200, NULL, NULL);

SELECT  
    E.EMPNO AS "Emp Number",  
    E.ENAME AS "Emp Name",  
    D.DNAME AS "Dept Name",  
    D.LOC AS "Dept Location" 
FROM  
    EMP E 
    LEFT JOIN DEPT D ON E.DEPTNO = D.DEPTNO;

SELECT  
    EMP.EMPNO AS "Employee Number",  
    EMP.ENAME AS "Employee Name",  
    EMP.HIREDATE AS "Hiredate",  
    MGR.ENAME AS "Mgr Name" 
FROM  
    EMP EMP 
    JOIN EMP MGR ON EMP.MGR = MGR.EMPNO 
WHERE  
    MGR.ENAME LIKE 'K%'  
    OR MGR.ENAME LIKE 'M%'  
    OR MGR.ENAME LIKE 'S%';

SELECT  
    E1.ENAME AS "Employee Name",  
    E1.DEPTNO AS "Department Number",  
    D.DNAME AS "Department Name",  
    E2.ENAME AS "Colleague Name" 
FROM  
    EMP E1 
    JOIN DEPT D ON E1.DEPTNO = D.DEPTNO 
    JOIN EMP E2 ON E1.DEPTNO = E2.DEPTNO 
WHERE  
    E1.ENAME = 'GIVEN_EMPLOYEE_NAME';

SELECT  
    D.DNAME AS "Department Name",  
    D.LOC AS "Location" 
FROM  
    EMP E 
    JOIN DEPT D ON E.DEPTNO = D.DEPTNO 
WHERE  
    E.JOB = 'CLERK';

INSERT INTO DEPT (DEPTNO, DNAME, LOC)  
VALUES (60, 'TRAINING', 'SAN FRANCISCO');

SELECT  
    E.EMPNO AS "Emp Number",  
    E.ENAME AS "Emp Name",  
    D.DNAME AS "Dept Name",  
    D.LOC AS "Dept Location" 
FROM  
    EMP E 
    JOIN DEPT D ON E.DEPTNO = D.DEPTNO 
WHERE  
    E.DEPTNO IN (20, 50);

INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)  
VALUES (8004, 'NEWEMP', 'CLERK', 7839, '15-OCT-2024', 1200, NULL, NULL);

SELECT  
    E.EMPNO AS "Emp Number",  
    E.ENAME AS "Emp Name",  
    D.DNAME AS "Dept Name",  
    D.LOC AS "Dept Location" 
FROM  
    EMP E 
    LEFT JOIN DEPT D ON E.DEPTNO = D.DEPTNO;

SELECT  
    EMP.EMPNO AS "Employee Number",  
    EMP.ENAME AS "Employee Name",  
    EMP.HIREDATE AS "Hiredate",  
    MGR.ENAME AS "Mgr Name" 
FROM  
    EMP EMP 
    JOIN EMP MGR ON EMP.MGR = MGR.EMPNO 
WHERE  
    MGR.ENAME LIKE 'K%'  
    OR MGR.ENAME LIKE 'M%'  
    OR MGR.ENAME LIKE 'S%';

SELECT  
    E1.ENAME AS "Employee Name",  
    E1.DEPTNO AS "Department Number",  
    D.DNAME AS "Department Name",  
    E2.ENAME AS "Colleague Name" 
FROM  
    EMP E1 
    JOIN DEPT D ON E1.DEPTNO = D.DEPTNO 
    JOIN EMP E2 ON E1.DEPTNO = E2.DEPTNO 
WHERE  
    E1.ENAME = 'KING';

SELECT  
    D.DNAME AS "Department Name",  
    D.LOC AS "Location" 
FROM  
    EMP E 
    JOIN DEPT D ON E.DEPTNO = D.DEPTNO 
WHERE  
    E.JOB = 'CLERK';

UPDATE DEPT  
SET DNAME = 'TRAINING', LOC = 'SAN FRANCISCO' 
WHERE DEPTNO = 60;

SELECT  
    E.EMPNO AS "Emp Number",  
    E.ENAME AS "Emp Name",  
    D.DNAME AS "Dept Name",  
    D.LOC AS "Dept Location" 
FROM  
    EMP E 
    JOIN DEPT D ON E.DEPTNO = D.DEPTNO 
WHERE  
    E.DEPTNO IN (20, 50);

INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)  
VALUES (8004, 'NEWEMP', 'CLERK', 7839, '15-OCT-2024', 1200, NULL, NULL);

SELECT  
    E.EMPNO AS "Emp Number",  
    E.ENAME AS "Emp Name",  
    D.DNAME AS "Dept Name",  
    D.LOC AS "Dept Location" 
FROM  
    EMP E 
    LEFT JOIN DEPT D ON E.DEPTNO = D.DEPTNO;

SELECT  
    EMP.EMPNO AS "Employee Number",  
    EMP.ENAME AS "Employee Name",  
    EMP.HIREDATE AS "Hiredate",  
    MGR.ENAME AS "Mgr Name" 
FROM  
    EMP EMP 
    JOIN EMP MGR ON EMP.MGR = MGR.EMPNO 
WHERE  
    MGR.ENAME LIKE 'K%'  
    OR MGR.ENAME LIKE 'M%'  
    OR MGR.ENAME LIKE 'S%';

SELECT  
    E1.ENAME AS "Employee Name",  
    E1.DEPTNO AS "Department Number",  
    D.DNAME AS "Department Name",  
    E2.ENAME AS "Colleague Name" 
FROM  
    EMP E1 
    JOIN DEPT D ON E1.DEPTNO = D.DEPTNO 
    JOIN EMP E2 ON E1.DEPTNO = E2.DEPTNO 
WHERE  
    E1.ENAME = 'KING';

SELECT  
    D.DNAME AS "Department Name",  
    D.LOC AS "Location" 
FROM  
    EMP E 
    JOIN DEPT D ON E.DEPTNO = D.DEPTNO 
WHERE  
    E.JOB = 'CLERK';

UPDATE DEPT  
SET DNAME = 'TRAINING', LOC = 'SAN FRANCISCO' 
WHERE DEPTNO = 60;

SELECT  
    E.EMPNO AS "Emp Number",  
    E.ENAME AS "Emp Name",  
    D.DNAME AS "Dept Name",  
    D.LOC AS "Dept Location" 
FROM  
    EMP E 
    JOIN DEPT D ON E.DEPTNO = D.DEPTNO 
WHERE  
    E.DEPTNO IN (20, 50);

